"""Conservation gate: the floor of the entire project.

Invariant #1 (root CLAUDE.md): for Target A, dY = nu @ phi must conserve baryon
number and satisfy charge-to-lepton closure to <= 1e-12 per step in float64 for
ANY flux vector phi — including random, untrained-network output. Accuracy affects
WHICH conserving update is produced, never WHETHER it conserves.

Two layers of tests:

1. A self-contained synthetic toy network (always runs, no pynucastro needed)
   with strong/EM columns plus one of EACH weak type (EC, beta-, beta+) and the
   full three-ledger lepton bookkeeping (e-, nu, nubar). If this fails, the
   constraint bookkeeping CONVENTION is wrong.

2. The exported production matrices (data/stoich/nu_mesa{80,151}.npz),
   auto-generated by the session fixture in conftest.py when absent — this
   layer NEVER skips. If it fails, the pynucastro export is wrong.
   Training must not begin until both layers pass (root CLAUDE.md gate).

Tolerance convention for random-flux drift (documented choice): the raw
1e-12 absolute gate is meaningful at O(1) fluxes but vacuous at phi ~ 1e-20,
so each drift is bounded by

    max(1e-12 * s, 1e-13 * G),   s = min(1, max|phi|),
                                 G = |A| . (|nu| @ |phi|)  (gross throughput)

i.e. the absolute CLAUDE.md gate at O(1) scale and a relative-to-gross bound
(~1000x looser than float64 eps accumulation) at the small end.
"""

from __future__ import annotations

import numpy as np
import pytest

from gnn_nucleo.data.schema import NETWORKS

TOL = 1e-12
RNG = np.random.default_rng(20260705)


# ----------------------------------------------------------------------------
# Layer 1: synthetic toy network with strong, EM, and all three weak types
# ----------------------------------------------------------------------------
#
# Species (index: name, A, Z):
#   0: n      (1, 0)
#   1: p      (1, 1)
#   2: he4    (4, 2)
#   3: c12    (12, 6)
#   4: mg24   (24, 12)
#   5: si28   (28, 14)
#   6: p31    (31, 15)
#   7: s32    (32, 16)
#   8: co55   (55, 27)
#   9: fe55   (55, 26)
#
# Reactions (columns of nu):
#   r0: triple-alpha        3 he4          -> c12
#   r1: alpha capture       c12  + 3 he4   -> mg24  (schematic chain link)
#   r2: (a,g)               mg24 + he4     -> si28
#   r3: (p,g)               p31  + p       -> s32          [bottleneck-like]
#   r4: (g,a) photodis.     si28           -> mg24 + he4
#   r5: EC (weak)           co55 + e-      -> fe55 + nu_e
#   r6: beta- (weak)        n              -> p + e- + nubar_e
#   r7: beta+ (weak)        co55           -> fe55 + e+ + nu_e
#                           (annihilated-positron convention: d_electron = -1)

A_VEC = np.array([1, 1, 4, 12, 24, 28, 31, 32, 55, 55], dtype=np.float64)
Z_VEC = np.array([0, 1, 2, 6, 12, 14, 15, 16, 27, 26], dtype=np.float64)

N_SPECIES = 10
N_REACTIONS = 8
WEAK_COLS = np.array([5, 6, 7])

NU = np.zeros((N_SPECIES, N_REACTIONS), dtype=np.float64)
NU[2, 0] = -3.0; NU[3, 0] = +1.0                       # 3a -> c12
NU[3, 1] = -1.0; NU[2, 1] = -3.0; NU[4, 1] = +1.0      # c12 + 3a -> mg24
NU[4, 2] = -1.0; NU[2, 2] = -1.0; NU[5, 2] = +1.0      # mg24(a,g)si28
NU[6, 3] = -1.0; NU[1, 3] = -1.0; NU[7, 3] = +1.0      # p31(p,g)s32
NU[5, 4] = -1.0; NU[4, 4] = +1.0; NU[2, 4] = +1.0      # si28(g,a)mg24
NU[8, 5] = -1.0; NU[9, 5] = +1.0                       # co55(EC)fe55
NU[0, 6] = -1.0; NU[1, 6] = +1.0                       # n(beta-)p
NU[8, 7] = -1.0; NU[9, 7] = +1.0                       # co55(beta+)fe55

# Lepton ledgers per reaction (assigned from the weak TYPE, never derived
# from Z @ nu — that would make the closure test a tautology):
#   EC:    d_e = -1, d_nu = +1, d_nubar = 0
#   beta-: d_e = +1, d_nu =  0, d_nubar = +1
#   beta+: d_e = -1, d_nu = +1, d_nubar = 0
D_ELECTRON = np.zeros(N_REACTIONS)
D_NEUTRINO = np.zeros(N_REACTIONS)
D_ANTINEUTRINO = np.zeros(N_REACTIONS)
D_ELECTRON[5], D_NEUTRINO[5] = -1.0, +1.0              # EC
D_ELECTRON[6], D_ANTINEUTRINO[6] = +1.0, +1.0          # beta-
D_ELECTRON[7], D_NEUTRINO[7] = -1.0, +1.0              # beta+


def _random_flux(n: int, scale_decades: float = 12.0) -> np.ndarray:
    """Signed fluxes spanning many decades — the realistic hostile input."""
    signs = RNG.choice([-1.0, 1.0], size=n)
    mags = 10.0 ** RNG.uniform(-scale_decades, 0.0, size=n)
    return signs * mags


def _drift_tol(phi: np.ndarray, A: np.ndarray, nu: np.ndarray) -> float:
    """max(1e-12 * s, 1e-13 * G) — see module docstring."""
    s = min(1.0, float(np.abs(phi).max()))
    gross = float(np.abs(A) @ (np.abs(nu) @ np.abs(phi)))
    return max(TOL * s, 1e-13 * gross)


def test_toy_baryon_conservation_any_flux():
    """Sum_i A_i * (nu @ phi)_i == 0 for arbitrary phi, to machine precision."""
    for _ in range(200):
        phi = _random_flux(N_REACTIONS)
        dY = NU @ phi
        assert abs(float(A_VEC @ dY)) <= TOL


def test_toy_charge_to_lepton_closure_any_flux():
    """Charge lost by nuclei in weak reactions is carried by leptons exactly."""
    for _ in range(200):
        phi = _random_flux(N_REACTIONS)
        dY = NU @ phi
        d_charge_nuclear = float(Z_VEC @ dY)
        d_electrons = float(D_ELECTRON @ phi)
        # Closure: nuclear charge change equals the electron-ledger change
        # (EC/beta+: -1; beta-: +1) — with ledgers assigned independently.
        assert abs(d_charge_nuclear - d_electrons) <= TOL


def test_toy_lepton_number_closes_per_weak_column():
    """(e-) + (nu) - (nubar) change is zero for every weak type."""
    for j in WEAK_COLS:
        dL = D_ELECTRON[j] + D_NEUTRINO[j] - D_ANTINEUTRINO[j]
        assert dL == 0.0, f"lepton number leaks in toy column {j}"


def test_toy_strong_columns_conserve_Z_columnwise():
    """Non-weak columns individually conserve nuclear charge."""
    for j in range(N_REACTIONS):
        if j in WEAK_COLS:
            continue
        assert abs(float(Z_VEC @ NU[:, j])) <= TOL
        assert abs(float(A_VEC @ NU[:, j])) <= TOL


@pytest.mark.parametrize(
    ("col", "expected_sign"),
    [(5, -1.0), (6, +1.0), (7, -1.0)],
    ids=["EC_lowers_Ye", "beta_minus_raises_Ye", "beta_plus_lowers_Ye"],
)
def test_toy_weak_column_moves_Ye_at_fixed_A(col, expected_sign):
    """The physical signal must survive: dYe != 0 through each weak column
    with the physically correct sign, while baryon number is untouched.
    A design that zeroes this to make the residuals vanish is wrong
    (invariant #3)."""
    phi = np.zeros(N_REACTIONS)
    phi[col] = 1e-6
    dY = NU @ phi
    dYe = float(Z_VEC @ dY)
    assert abs(float(A_VEC @ dY)) <= TOL           # A conserved exactly
    assert dYe * expected_sign > 0                  # correct direction
    assert abs(dYe - expected_sign * 1e-6) <= 1e-18  # one charge unit * phi


def test_toy_mask_never_touches_weak_columns():
    """Invariant #2: gating scales columns; column sums vanish regardless of the
    gate — but weak columns must never be in the eligible set at all."""
    gate = RNG.uniform(0.0, 1.0, size=N_REACTIONS)
    eligible = np.ones(N_REACTIONS, dtype=bool)
    eligible[WEAK_COLS] = False  # this line is the contract under test
    effective = np.where(eligible, gate, 1.0)
    phi = _random_flux(N_REACTIONS)
    dY = NU @ (effective * phi)
    assert abs(float(A_VEC @ dY)) <= TOL
    # weak fluxes passed through unscaled:
    assert all(effective[j] == 1.0 for j in WEAK_COLS)


# ----------------------------------------------------------------------------
# Layer 2: exported production matrices (mesa_80 / mesa_151) — never skips;
# the conftest fixture regenerates a missing npz from pynucastro (~7 s/net).
# ----------------------------------------------------------------------------

#: phi magnitude scales for the drift sweep — spans the realistic 20-decade
#: abundance-change range down to where only the relative bound is meaningful.
SCALES = (1e0, 1e-4, 1e-8, 1e-12, 1e-16, 1e-20)
N_SEEDS = 10


def test_exported_shapes_and_species(stoich_export):
    network, d = stoich_export
    nu = d["nu"]
    n_species, n_reactions = nu.shape
    assert n_species == NETWORKS[network]
    assert d["A"].shape == d["Z"].shape == (n_species,)
    assert d["weak_mask"].shape == d["d_electron"].shape == (n_reactions,)
    assert d["nu_ext"].shape == (n_species + 3, n_reactions)
    assert d["C"].shape == (3, n_species + 3)


def test_exported_columns_conserve_exactly(stoich_export):
    """Column-wise exactness: entries are small integers, so the sums are
    exact in float64 — zero tolerance, any leak names its reaction."""
    network, d = stoich_export
    nu, A, Z = d["nu"], d["A"], d["Z"]
    weak = d["weak_mask"].astype(bool)
    names = d["rate_fnames"]

    dA = A @ nu
    dq = Z @ nu
    for j in range(nu.shape[1]):
        assert dA[j] == 0.0, f"{network}: baryon leak in {names[j]}"
        if weak[j]:
            assert abs(dq[j]) == 1.0, f"{network}: weak |dZ| != 1 in {names[j]}"
            assert dq[j] == d["d_electron"][j], f"{network}: lepton closure fails in {names[j]}"
        else:
            assert dq[j] == 0.0, f"{network}: charge leak in {names[j]}"


def test_exported_lepton_ledgers_close(stoich_export):
    """Lepton number closes per weak column; ledgers are zero on strong
    columns; C @ nu_ext == 0 exactly (all three constraint rows)."""
    network, d = stoich_export
    weak = d["weak_mask"].astype(bool)
    d_e, d_nu, d_nubar = d["d_electron"], d["d_neutrino"], d["d_antineutrino"]

    dL = d_e + d_nu - d_nubar
    assert np.all(dL[weak] == 0.0), f"{network}: lepton number leaks in weak columns"
    for arr in (d_e, d_nu, d_nubar):
        assert np.all(arr[~weak] == 0.0), f"{network}: lepton ledger on a strong column"

    residual = np.abs(d["C"] @ d["nu_ext"]).max()
    assert residual == 0.0, f"{network}: C @ nu_ext residual {residual}"


def test_exported_weak_mask_matches_weak_type(stoich_export):
    network, d = stoich_export
    weak = d["weak_mask"].astype(bool)
    wt = d["weak_type"]
    assert np.array_equal(weak, wt != ""), f"{network}: weak_mask/weak_type disagree"
    assert set(np.unique(wt[weak])) <= {"electron_capture", "beta_neg", "beta_pos"}


@pytest.mark.parametrize("scale", SCALES)
def test_exported_random_flux_drift(stoich_export, scale):
    """THE blocking gate: random phi (many seeds, this magnitude scale) must
    conserve baryon number and close charge-to-lepton within
    max(1e-12 * s, 1e-13 * G) — see module docstring for the tolerance
    rationale — while moving Ye through the weak columns."""
    network, d = stoich_export
    nu, A, Z = d["nu"], d["A"], d["Z"]
    weak = d["weak_mask"].astype(bool)
    d_e = d["d_electron"]
    n_r = nu.shape[1]

    for seed in range(N_SEEDS):
        rng = np.random.default_rng(1000 * seed + int(-np.log10(scale)))
        phi = scale * rng.choice([-1.0, 1.0], n_r) * 10.0 ** rng.uniform(-3, 0, n_r)
        tol = _drift_tol(phi, A, nu)

        dY = nu @ phi
        baryon_drift = abs(float(A @ dY))
        assert baryon_drift <= tol, (
            f"{network} seed {seed} scale {scale:g}: baryon drift {baryon_drift:.3e} > {tol:.3e}"
        )
        closure = abs(float(Z @ dY) - float(d_e @ phi))
        assert closure <= tol, (
            f"{network} seed {seed} scale {scale:g}: charge-to-lepton {closure:.3e} > {tol:.3e}"
        )

        # The physics must survive (invariant #3): weak-only flux moves Ye.
        phi_weak = np.where(weak, phi, 0.0)
        assert phi_weak.any()
        dYe_weak = float(Z @ (nu @ phi_weak))
        assert dYe_weak != 0.0, f"{network} seed {seed}: dYe zero through weak columns"


def test_exported_mask_contract_on_real_matrix(stoich_export):
    """Invariant #2 on the production matrix: the eligible set is built
    structurally from weak_mask; weak columns pass through any gate unscaled
    and conservation holds regardless of the gate values."""
    network, d = stoich_export
    nu, A = d["nu"], d["A"]
    weak = d["weak_mask"].astype(bool)
    n_r = nu.shape[1]

    gate = RNG.uniform(0.0, 1.0, size=n_r)
    eligible = ~weak  # the contract under test: structural, not conventional
    effective = np.where(eligible, gate, 1.0)
    phi = _random_flux(n_r)
    dY = nu @ (effective * phi)
    assert abs(float(A @ dY)) <= _drift_tol(effective * phi, A, nu)
    assert np.all(effective[weak] == 1.0)
